[GLUTEN-5108][CH] Fix the classes in the hadoop-common conflict when running ut local (#5109)
Fix the classes in the hadoop-common conflict when running ut local.

Env: Idea + Spark 3.3 + Hadoop 3.3.1
UT: GlutenClickHouseMergeTreeWriteOnS3Suite / GlutenClickHouseMergeTreeWriteOnHDFSSuite
Error:
```
java.lang.NoClassDefFoundError: xxxxx
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:634)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
```

RC:
The jar `hive-hcatalog-core` includes the hadoop-common 2.7.2 and hadoop-hdfs 2.7.2, which conflict with the hadoop 3.3.1 when running ut with hadoop-3.3 profile.

Close #5108.