[VL] Fix clang does not support stringop-overflow flag (#10136)
Clang does not support stringop-overflow flag.
error: unknown warning option '-Werror=stringop-overflow'; did you mean '-Werror=shift-overflow'? [-Werror,-Wunknown-warning-option]